### ISSUE TITLE
HDC_DUC model - gridding effect

### ISSUE THREAD

**Issue by sagarr** [MEDAL-IITB/Lung-Segmentation#1]
Hi, Did you get "gridding effect" while training your HDC DUC model? I'm getting something like this output: (The below white part is GT, the above part is prediction)
![image](https://user-images.githubusercontent.com/1051004/49144432-6218d680-f323-11e8-918b-3cd9a6485ab1.png)

**Comment by kateverdeen** [comment]
Apologies for the late reply. We didn't get any gridding effect like you mentioned above while training the model.

**Comment by sagarr** [comment]
no worries, just after few days come to know its well known issue while using dilated convolution
